name = "Probker"
uuid = "d0ae23fd-a9a3-4625-bb1d-fa5e90ff7a39"
authors = ["Christian Brunbjerg Jespersen <brunbjerg1423@live.dk> and contributors"]
version = "0.1.0"

[deps]
GenieDeployDocker = "a082159f-dd50-4f6d-a3c5-00c38fd36577"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
